@echo off

sqlite3 NASB.db "DROP TABLE BookFormat;"
sqlite3 NASB.db "CREATE TABLE BookFormat (BookIndex int, Chapters int, StandardBookOrder int, StandardBookGroup int, HebrewBookOrder int, HebrewBookGroup int, GroupEnd int, Name string, NameAbbrev string);"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(1, 50,       1, 1,         1, 0,         0,      'Genesis', 'Gen');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(2, 40,       2, 1,         2, 0,         0,      'Exodus', 'Exo');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(3, 27,       3, 1,         3, 0,         0,      'Leviticus', 'Lev');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(4, 36,       4, 1,         4, 0,         0,      'Numbers', 'Num');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(5, 34,       5, 1,         5, 0,         1,      'Deuteronomy', 'Deu');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(6, 48,       6, 2,         6, 0,         0,      'Joshua', 'Jos');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(7, 46,       7, 2,         7, 0,         0,      'Judges', 'Jud');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(8,  7,       8, 2,         31, 0,        1,      'Ruth', 'Rut');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(9, 31,       9, 3,         8, 0,         0,      '1 Samuel', '1Sam');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(10, 24,      10, 3,        9, 0,         0,      '2 Samuel', '2Sam');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(11, 22,      11, 3,       10, 0,         0,      '1 Kings', '1Kin');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(12, 25,      12, 3,       11, 0,         0,      '2 Kings', '2Kin');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(13, 29,      13, 3,       38, 0,         0,      '1 Chronicles', '1Chr');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(14, 36,      14, 3,       39, 0,         1,      '2 Chronicles', '2Chr');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(15, 10,      15, 4,       36, 0,         0,      'Ezra', 'Ezr');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(16, 13,      16, 4,       37, 0,         0,      'Nememiah', 'Nem');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(17, 10,      17, 4,       34, 0,         1,      'Esther', 'Est');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(18, 42,      18, 5,       29, 0,         0,      'Job', 'Job');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(19, 150,     19, 5,       27, 0,         0,      'Psalms', 'Psa');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(20, 31,      20, 5,       29, 0,         0,      'Proverbs', 'Pro');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(21, 11,      21, 5,       33, 0,         0,      'Ecclesiates', 'Ecc');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(22,  8,      22, 5,       30, 0,         1,      'Songs of Songs', 'Son');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(23, 66,      23, 6,       12, 0,         0,      'Isaiah', 'Isa');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(24, 52,      24, 6,       13, 0,         0,      'Jeremiah', 'Jer');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(25,  5,      25, 6,       32, 0,         0,      'Lamentations', 'Lam');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(26, 48,      26, 6,       14, 0,         0,      'Ezekiel', 'Eze');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(27, 12,      27, 6,       35, 0,         1,      'Daniel', 'Dan');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(28, 14,      28, 7,       15, 0,         0,      'Hosea', 'Hos');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(29,  3,      29, 7,       16, 0,         0,      'Joel', 'Joe');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(30,  9,      30, 7,       17, 0,         0,      'Amos', 'Amo');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(31,  1,      31, 7,       18, 0,         0,      'Obadiah', 'Oba');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(32,  3,      32, 7,       19, 0,         0,      'Jonah', 'Jona');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(33,  7,      33, 7,       20, 0,         0,      'Micah', 'Mic');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(34,  3,      34, 7,       21, 0,         0,      'Nahum', 'Nah');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(35,  3,      35, 7,       22, 0,         0,      'Habkkuk', 'Hab');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(36,  3,      36, 7,       23, 0,         0,      'Zepheniah', 'Zep');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(37,  2,      37, 7,       24, 0,         0,      'Haggai', 'Hag');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(38, 14,      38, 7,       25, 0,         0,      'Zechariah', 'Zec');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(39,  4,      39, 7,       26, 0,         1,      'Malachi', 'Mal');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(40, 28,      40, 8,       40, 0,         0,      'Matthew', 'Matt');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(41, 16,      41, 8,       41, 0,         0,      'Mark', 'Mark');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(42, 24,      42, 8,       42, 0,         0,      'Luke', 'Luke');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(43, 21,      43, 8,       43, 0,         1,      'John', 'John');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(44, 28,      44, 9,       44, 0,         1,      'Acts', 'Acts');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(45, 16,      45, 10,      45, 0,         0,      'Romans', 'Rom');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(46, 16,      46, 10,      46, 0,         0,      '1 Corinthians', '1Cor');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(47, 13,      47, 10,      47, 0,         0,      '2 Corinthians', '2Cor');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(48,  6,      48, 10,      48, 0,         0,      'Galatians', 'Gal');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(49,  6,      49, 10,      49, 0,         0,      'Ephesians', 'Eph');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(50,  4,      50, 10,      50, 0,         0,      'Philippians', 'Phi');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(51,  4,      51, 10,      51, 0,         0,      'Colossians', 'Col');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(52,  5,      52, 10,      52, 0,         0,      '1 Thessalonians', '1The');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(53,  3,      53, 10,      53, 0,         1,      '2 Thessalonians', '2The');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(54,  6,      54, 11,      54, 0,         0,      '1 Timothy', '1Tim');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(55,  4,      55, 11,      55, 0,         0,      '2 Timothy', '2Tim');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(56,  3,      56, 11,      56, 0,         0,      'Titus', 'Tit');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(57,  1,      57, 11,      57, 0,         1,      'Philemon', 'Phi');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(58, 13,      58, 12,      58, 0,         1,      'Hebrews', 'Heb');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(59,  5,      59, 13,      59, 0,         0,      'James', 'Jam');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(60,  5,      60, 13,      60, 0,         0,      '1 Peter', '1Pet');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(61,  3,      61, 13,      61, 0,         0,      '1 Peter', '2Pet');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(62,  5,      62, 13,      62, 0,         0,      '1 John', '1John');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(63,  1,      63, 13,      63, 0,         0,      '2 John', '2John');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(64,  1,      64, 13,      64, 0,         0,      '3 John', '3John');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(65,  1,      65, 13,      65, 0,         1,      'Jude', 'Jude');"
sqlite3 NASB.db "INSERT INTO BookFormat VALUES(66, 22,      66, 14,      66, 0,         0,      'Revelation', 'Rev');"
